apiVersion: batch/v1
kind: CronJob
metadata:
  name: imagecropper
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: imagecropper
            image: {{ .Values.image }}
            imagePullPolicy: IfNotPresent
            env:
              - name: GOOGLE_APP_CREDENTIALS
                valueFrom:
                  secretKeyRef:
                    key: GOOGLE_APP_CREDENTIALS
                    name: {{ .Values.secretName }}
              - name: IC_BUCKET_NAME
                valueFrom:
                  secretKeyRef:
                    key: IC_BUCKET_NAME
                    name: {{ .Values.secretName }}
              - name: CLOUDINARY_URL
                valueFrom:
                  secretKeyRef:
                    key: CLOUDINARY_URL
                    name: {{ .Values.secretName }}
              - name: SMB_USERNAME
                valueFrom:
                  secretKeyRef:
                    key: SMB_USERNAME
                    name: {{ .Values.secretName }}
              - name: SMB_PASSWORD
                valueFrom:
                  secretKeyRef:
                    key: SMB_PASSWORD
                    name: {{ .Values.secretName }}
              - name: SMB_SERVER
                valueFrom:
                  secretKeyRef:
                    key: SMB_SERVER
                    name: {{ .Values.secretName }}
              - name: SMB_SHARE
                valueFrom:
                  secretKeyRef:
                    key: SMB_SHARE
                    name: {{ .Values.secretName }}
              - name: TARGET_IMAGE_WIDTH
                value: { { .Values.targetImageWidth } }
              - name: TARGET_IMAGE_HEIGHT
                value: { { .Values.targetImageHeight } }
          restartPolicy: OnFailure

          imagePullSecrets:
            - name: {{ .Values.registrySecretName }}
