apiVersion: batch/v1
kind: CronJob
metadata:
  name: imagecropper
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: data-volume
              persistentVolumeClaim:
                claimName: imagecropper-data

          containers:
          - name: imagecropper
            image: {{ .Values.image }}
            imagePullPolicy: IfNotPresent
            env:
              - name: GOOGLE_APP_CREDENTIALS
                valueFrom:
                  secretKeyRef:
                    key: GOOGLE_APP_CREDENTIALS
                    name: {{ .Values.secretName }}
              - name: IC_BUCKET_NAME
                valueFrom:
                  secretKeyRef:
                    key: IC_BUCKET_NAME
                    name: {{ .Values.secretName }}
              - name: IC_ALBUM_SECRET
                valueFrom:
                  secretKeyRef:
                    key: IC_ALBUM_SECRET
                    name: {{ .Values.secretName }}
              - name: IC_ALBUM_ID
                valueFrom:
                  secretKeyRef:
                    key: IC_ALBUM_ID
                    name: {{ .Values.secretName }}
              - name: CLOUDINARY_URL
                valueFrom:
                  secretKeyRef:
                    key: CLOUDINARY_URL
                    name: {{ .Values.secretName }}
            volumeMounts:
                - name: data-volume
                  mountPath: /data
          restartPolicy: OnFailure

          imagePullSecrets:
            - name: {{ .Values.registrySecretName }}
