apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: imagecropper
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: imagecropper
            image: {{ .Values.image }}
            imagePullPolicy: Always
            env:
              - name: GOOGLE_APP_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  key: GOOGLE_APP_CREDENTIALS
                  name: {{ .Values.secretName }}
              - name: IC_BUCKET_NAME
                valueFrom:
                  secretKeyRef:
                    key: IC_BUCKET_NAME
                    name: {{ .Values.secretName }}
              - name: IC_ALBUM_SECRET
                valueFrom:
                  secretKeyRef:
                    key: IC_ALBUM_SECRET
                    name: {{ .Values.secretName }}
              - name: IC_ALBUM_ID
                valueFrom:
                  secretKeyRef:
                    key: IC_ALBUM_ID
                    name: {{ .Values.secretName }}
          restartPolicy: OnFailure
